
networks:
  toubeelib.net:
    driver: bridge
services:
  # service api.toubeelib : api pour la prise de rdv
  #
  api.toubeelib:
  #  image: 'canals/php:8.3-cli'
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    env_file: ./toubeelib.env
    ports:
      - '6080:80'
    volumes:
      - ./toubeelib/app:/var/php
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.db
    command: php -S 0.0.0.0:80 -t /var/php/public

    # service toubeelib.db : base de données postgresql
  toubeelib.db:
    image: 'postgres:latest'
    env_file: ./toubeelibdb.env
    ports:
      - '5432:5432'
    networks:
      - toubeelib.net
    volumes:
      - ./toubeelib/app/sql:/docker-entrypoint-initdb.d

  praticien.db:
    image: 'postgres:latest'
    env_file: ./praticiendb.env
    ports:
      - '5433:5432'
    networks:
      - toubeelib.net
    volumes:
      - ./toubeelib/app/sql/praticien:/docker-entrypoint-initdb.d
    
  patient.db:
    image: 'postgres:latest'
    env_file: ./patientdb.env
    ports:
      - '5434:5432'
    networks:
      - toubeelib.net
    volumes:
      - ./toubeelib/app/sql/patient:/docker-entrypoint-initdb.d

  auth.db:
    image: 'postgres:latest'
    env_file: ./authdb.env
    ports:
      - '5435:5432'
    networks:
      - toubeelib.net
    volumes:
      - ./toubeelib/app/sql/auth:/docker-entrypoint-initdb.d

  rdv.db:
    image: 'postgres:latest'
    env_file: ./rdvdb.env
    ports:
      - '5436:5432'
    networks:
      - toubeelib.net
    volumes:
      - ./toubeelib/app/sql/rdv:/docker-entrypoint-initdb.d
  #
  # service administration des bases sql
  #
  adminer:
    image: adminer
    ports:
      - '8080:8080'
    networks:
      - toubeelib.net


  ############################################
  #    deuxieme service php pour gateway
  ############################################
  gateway.toubeelib:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    env_file: ./toubeelib.env
    ports:
      - '6081:80'
    volumes:
      - ./toubeelib/gateway:/var/php
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.db
    command: php -S 0.0.0.0:80 -t /var/php/public


  ############################################
  #    service php pour app-praticiens
  ############################################
  api.praticiens:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile
    env_file: ./toubeelib.env
    ports:
      - '6082:80'
    volumes:
      - ./app-praticiens/gateway:/var/php
    working_dir: /var/php
    networks:
      - toubeelib.net
    depends_on:
      - toubeelib.db
    command: php -S 0.0.0.0:80 -t /var/php/public

